# Generated by Django 3.1.2 on 2020-11-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posting',
        ),
        migrations.AlterModelTable(
            name='posting',
            table='postings',
        ),
    ]
